// <auto-generated />
using EVA2TI_BarPinguino.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVA2TI_BarPinguino.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250108203127_corregirUsuarios")]
    partial class corregirUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Clientes", b =>
                {
                    b.Property<string>("Rut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frecuente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Rut");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Descuentos", b =>
                {
                    b.Property<int>("SKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SKU"));

                    b.Property<string>("Precio_descuento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Precio_original")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SKU");

                    b.ToTable("Descuentos", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Finanzas", b =>
                {
                    b.Property<string>("I_stock")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gasto")
                        .HasColumnType("int");

                    b.Property<int>("Informe_stock")
                        .HasColumnType("int");

                    b.Property<int>("Num_Boleta")
                        .HasColumnType("int");

                    b.Property<string>("ingreso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("n_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("I_stock");

                    b.HasIndex("Informe_stock");

                    b.HasIndex("n_documento");

                    b.ToTable("Finanzas", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Proveedores", b =>
                {
                    b.Property<string>("Rut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Fono")
                        .HasColumnType("int");

                    b.Property<string>("Giro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("datos_bancarios")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("razon_social")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Rut");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Stock", b =>
                {
                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<string>("Informe_stock")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Stock_critico")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Sku");

                    b.HasIndex("Provedor");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Usuarios", b =>
                {
                    b.Property<int>("Credencial_vendedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Credencial_vendedor");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Venta", b =>
                {
                    b.Property<string>("Num_Boleta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Credencial_v")
                        .HasColumnType("int");

                    b.Property<int>("Credencial_vendedor")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rut")
                        .HasColumnType("int");

                    b.Property<int>("TotalPedido")
                        .HasColumnType("int");

                    b.Property<string>("cliente_rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Num_Boleta");

                    b.HasIndex("Credencial_vendedor");

                    b.HasIndex("cliente_rut");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Finanzas", b =>
                {
                    b.HasOne("EVA2TI_BarPinguino.Models.Stock", "Stock")
                        .WithMany("Finanzas")
                        .HasForeignKey("Informe_stock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVA2TI_BarPinguino.Models.Venta", "Venta")
                        .WithMany("Finanzas")
                        .HasForeignKey("n_documento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Stock", b =>
                {
                    b.HasOne("EVA2TI_BarPinguino.Models.Proveedores", "Proveedores")
                        .WithMany("Stock")
                        .HasForeignKey("Provedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVA2TI_BarPinguino.Models.Descuentos", "Descuentos")
                        .WithMany("Stock")
                        .HasForeignKey("Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descuentos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Venta", b =>
                {
                    b.HasOne("EVA2TI_BarPinguino.Models.Usuarios", "Usuarios")
                        .WithMany("Venta")
                        .HasForeignKey("Credencial_vendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVA2TI_BarPinguino.Models.Clientes", "Clientes")
                        .WithMany("Venta")
                        .HasForeignKey("cliente_rut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Clientes", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Descuentos", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Proveedores", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Stock", b =>
                {
                    b.Navigation("Finanzas");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Usuarios", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EVA2TI_BarPinguino.Models.Venta", b =>
                {
                    b.Navigation("Finanzas");
                });
#pragma warning restore 612, 618
        }
    }
}
